---
title: "Análisis DSE: multinivel"
author: "Equipo EDUMER"
fontsize: 14pt
#bibliography: "../input/mini-proyecto.bib"
#csl: "input/bib/apa6.csl"
format:
  html:
    toc: true
    toc-location: right
    toc-depth: 6
    toc-expand: 6
    toc-title: Contenidos
    number-sections: false
    number-depth: 6
    theme: 
    - edumer.scss
    - sandstone
    title-block-banner: true
editor: visual
lang: es
---

```{r data}
#| echo: false
pacman::p_load(dplyr, sjPlot, stargazer, kableExtra, texreg, haven, sjlabelled, ggplot2, summarytools, ggtext, ggpubr, hrbrthemes, tidyr, stringr, sjmisc, ggalluvial, shadowtext, sjmisc, lme4, Matrix)

# cargamos datos long 
load("../input/data/proc/proc_w02.RData")

```


```{r}
#| echo: false
 
# paso 1: se crea un diccionario para poder distinguir las caracteristicas de las viñetas
diccionario_viñetas <- tibble(
  variable = c("exp_t4_a", "exp_t4_b", "exp_t4_c", "exp_t4_d"),
  descripcion_viñeta = c(
  "Se esfuerza más que la mayoría - Su casa es pequeña, no tiene un espacio cómodo para estudiar", 
  "Se esfuerza menos que la mayoría - Su casa es grande, tiene un espacio cómodo para estudiar", 
  "Se esfuerza más que la mayoría - Su casa es grande, tiene un espacio cómodo para estudiar", 
  "Se esfuerza menos que la mayoría - Su casa es pequeña, no tiene un espacio cómodo para estudiar"))


# paso 2: 
datos_viñetas <- datos %>%
  pivot_longer(cols = starts_with("exp_t4_"),
               names_to = "variable", 
               values_to = "decimas_asignadas")


# paso 3: 
datos_viñetas <- datos_viñetas %>%
  left_join(diccionario_viñetas, by = "variable")

# paso 4: se distinguen las dos caracteristicas que compone la viñeta en variables individuales
datos_viñetas <- datos_viñetas %>%
  separate(descripcion_viñeta, into = c("esfuerzo", "contexto_hogar"), sep = " - ")

#d <- datos %>% select(id_estudiante, variable, decimas_asignadas, esfuerzo, contexto_hogar, prop_decimas)


# calcular las décimas como proporciones 
datos_viñetas <- datos_viñetas %>%
  group_by(id_estudiante) %>%
  mutate(total_decimas = sum(decimas_asignadas)) %>%
  ungroup()

datos_viñetas <- datos_viñetas %>%
  mutate(prop_decimas = decimas_asignadas / total_decimas)

#summary(datos$prop_decimas)
```

## Univariados

```{r}
#| echo: false
#| label: univariados

print(summarytools::dfSummary(datos), method="render")
```


## Correlaciones 

### Proporciones

```{r}
#| echo: false
#| label: correlacion con proporciones
#| message: false
#| warning: false

M1 <- datos_viñetas %>% select(genero, curso, 
                                                merit_esfuerzo,
                              merit_talento,
                              school_esfuerzo,
                              school_talento,
                              school_merecimiento, esfuerzo, 
                              contexto_hogar, prop_decimas) %>% na.omit() %>%  mutate_all(~(as.numeric(.)))

M1 <- cor(M1)

#Plot the matrix using corrplot
 #corrplot::corrplot(M1,
                #   method = "color",
                 #  addCoef.col = "black",
                  # type = "upper",
                   #tl.col = "black",
                  # col = colorRampPalette(c("#E16462", "white", "#0D0887"))(12),
                  # bg = "white",
                  # na.label = "-")
 
 sjPlot::tab_corr(M1, 
                 triangle = "lower")

```


### Décimas

```{r}
#| echo: false
#| label: correlacion con décimas

M <- datos_viñetas %>% select(genero, curso, 
                                                            merit_esfuerzo,
                              merit_talento,
                              school_esfuerzo,
                              school_talento,
                              school_merecimiento, decimas_asignadas) %>% na.omit() %>%  mutate_all(~(as.numeric(.)))

M <- cor(M)

#Plot the matrix using corrplot
 #corrplot::corrplot(M,
  #                 method = "color",
   #                addCoef.col = "black",
    #               type = "upper",
     #              tl.col = "black",
      #             col = colorRampPalette(c("#E16462", "white", "#0D0887"))(12),
                #   bg = "white",
                 #  na.label = "-")
 
 sjPlot::tab_corr(M, 
                 triangle = "lower")

```


## Modelos simples

### Proporciones 

```{r}
#| echo: false


```


### Décimas

```{r}
#| echo: false
#| message: false
#| warning: false

r1 <- lmer(decimas_asignadas ~ genero +  (1 | id_estudiante), data = datos_viñetas)

r2 <- lmer(decimas_asignadas ~ curso + (1 | id_estudiante), data = datos_viñetas)

r3 <- lmer(decimas_asignadas ~ libros_hogar + (1 | id_estudiante), data = datos_viñetas)

r4 <- lmer(decimas_asignadas ~ merit_esfuerzo + (1 | id_estudiante), data = datos_viñetas)

r5 <- lmer(decimas_asignadas ~ merit_talento + (1 | id_estudiante), data = datos_viñetas)

r6 <- lmer(decimas_asignadas ~ school_esfuerzo + (1 | id_estudiante), data = datos_viñetas)

r7 <- lmer(decimas_asignadas ~ school_talento + (1 | id_estudiante), data = datos_viñetas)

r8 <- lmer(decimas_asignadas ~ school_merecimiento + (1 | id_estudiante), data = datos_viñetas)

#exreg::htmlreg(list(r1, r2, r3, r4, r5, r6, r7,r8))

sjPlot::tab_model(list(r1, r2, r3, r4, r5, r6, r7,r8), show.ci=FALSE)
```


## Modelos multinivel


```{r}
#| echo: false

# m. multinivel
#data <- datos_viñetas %>% 
 # select(prop_decimas, decimas_asignadas, esfuerzo, contexto_hogar, genero, curso, libros_hogar, merit_esfuerzo=p1_1, merit_talento=p1_2, escuela_esfuerzo=p2_1, escuela_talento=p2_2, escuela_merecimiento=p2_3, id_estudiante) %>% 
 # na.omit()

datos_viñetas$esfuerzo <- factor(datos_viñetas$esfuerzo,
                        levels = c("Se esfuerza menos que la mayoría",
                                   "Se esfuerza más que la mayoría"))

table(datos_viñetas$esfuerzo)


```

```{r}
#| echo: false
#| results: 'asis'

reg1 <- lmer(decimas_asignadas ~ esfuerzo + contexto_hogar + (1 | id_estudiante), data = datos_viñetas)

reg1 <- lmer(decimas_asignadas ~ esfuerzo + contexto_hogar + (1 | id_estudiante), data = datos_viñetas)

reg2 <- lmer(decimas_asignadas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + (1 | id_estudiante), data = datos_viñetas)
reg3 <- lmer(decimas_asignadas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + merit_esfuerzo + merit_talento + school_esfuerzo + school_talento + school_merecimiento + (1 | id_estudiante), data = datos_viñetas)
reg4 <- lmer(decimas_asignadas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + merit_esfuerzo + merit_talento + school_esfuerzo + school_talento + school_merecimiento + (1 | id_estudiante), data = datos_viñetas)

texreg::htmlreg(list(reg1, reg2, reg3))
```

```{r}
#| echo: false
#| results: 'asis'

reg1 <- lmer(prop_decimas ~ esfuerzo + contexto_hogar + (1 | id_estudiante), data = datos_viñetas)

reg2 <- lmer(prop_decimas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + (1 | id_estudiante), data = datos_viñetas)

reg3 <- lmer(prop_decimas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + merit_esfuerzo + merit_talento +school_esfuerzo + school_talento + school_merecimiento + (1 | id_estudiante), data = datos_viñetas)

reg4 <- lmer(prop_decimas ~ esfuerzo + contexto_hogar + genero + curso + libros_hogar + merit_esfuerzo + merit_talento + school_esfuerzo + school_talento + school_merecimiento + (1 | id_estudiante), data = datos_viñetas)

texreg::htmlreg(list(reg1, reg2, reg3))
```

